### PR TITLE
Short README, full docs on the website.

### PR DESCRIPTION
**Pull request by kciesielski**
Current compiler output examples are:
1. incorrectly encoded as ```scala which adds weird colors
2. a bit outdated (link to Akka docs is for experimental)
3. not reflecting full power of awesome colors :)

This PR adds examples as images to address all that.

### CODE REVIEW

**Comment by adamw** [comment]
What about the main page? Or maybe it would be possible to merge these two and show the readme on the web page or vice versa?

**Comment by kciesielski** [comment]
Good idea, I'll add this there.

**Comment by kciesielski** [comment]
I think many GH projects have very short README just pointing to the rich doc site if there's one. I'd go with adding all the details to the main page and leave only a short description in README + link, wdyt?

**Comment by adamw** [comment]
@kciesielski sounds good :)

**Comment by adamw** [comment]
Deployed :)

**Pull request merged**
